config/routes.rb
Hsd::Application.routes.draw do
  root :to => "pages#home"

  resources :pages do
    resources :versions, :controller => "pages/versions"
    resources :attachments, :controller => "pages/attachments"
  end
  resources :tags
  resources :changes

  resources :files do
    get '*path', :action => 'show', :on => :collection
  end
  
  namespace :admin do
    resources :users do
      post :confirm, :on => :member
    end
  end

  resource :search, :controller => :search

  get "/sign_in", to:"sessions#new", as:"sign_in"
  get "/sign_out", to:"sessions#destroy", as:"sign_out"
  post "/welcome", to:"sessions#unlock", as:"unlock"
  match '/auth/:provider/callback', to:'sessions#create'
  match '/auth/failure', to:'sessions#failure'

  match "/index.html" => redirect("/")
  get '/home' => redirect("/")
  
  get    ':id' => 'pages#show', :as => :page
  put    ':id' => 'pages#update'
  delete ':id' => 'pages#destroy'
end

app/views/pages/_form.html.erb
<%= f.hidden_field :version %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name, tabindex:1, class:"span12" %>
</div>

<div>
  <span class="help-inline pull-right">Learn how to format this page by looking at <%= link_to "textile documentation", "http://www.textism.com/tools/textile/", target:"_blank" %></span>
  <%= f.label :body %>
  <%= f.text_area :body, tabindex:2, rows:20, class:"span12" %>
</div>
<br/>

<div>
  <span class="help-inline pull-right">Select the tags below that apply to this page or <%= link_to "add your own", tags_path %></span>
  <label>
    Tags
  </label>

  <div class="controls tags">
    <% @page.tags.each do |tag| %>
    <%= tag_selector tag, true %>
    <% end %>
    <% (Tag.all - @page.tags).each do |tag| %>
    <%= tag_selector tag, false %>
    <% end %>
  </div>

  <%= f.select :tag_ids, options_from_collection_for_select(Tag.all, :id, :name, @page.tags.map(&:id)), {}, multiple:true, size:6, style:"opacity:0;position:absolute;left:-400px;" %>
</div>
<br/>

<div>
  <%= f.label :thumbnail %>
  <div><%= image_tag @page.thumbnail.url(:tiny) if @page.thumbnail? %></div>
  <%= f.file_field :thumbnail %>
</div>
<br/>

<div class="form-actions">
  <div class="pull-right">
    <%= link_to "Cancel", page_path(@page), class:"btn" %>
    <%= f.submit "Save", disable_with:'Saving...', tabindex:3, class:"btn btn-primary" %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
$(function() {
  $(".tags .tag").click(function() {
    var tag = $(this);
    var tagOption = $("#page_tag_ids option[value='" + tag.attr("tagId") + "']");
    
    if (tag.hasClass("label-info")) {
      tag.removeClass("label-info");
      tagOption.attr("selected", null);

    } else {
      tag.addClass("label-info");
      tagOption.attr("selected", "selected");
    }
    return false;
  });
});
</script>

app/views/pages/_page_list.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>Tags</th>
    <th></th>
  </tr>
  <% @pages.each do |page| %>
    <tr>
      <td>
        <%= link_to page.name, page_path(page) %> 
      </td>
      <td>
        <% page.tags.each do |tag| %><%= link_to tag.name, tag, class:"label label-info" %> <% end %>
      </td>
      <td>
        <% if can_edit? %>
          <%= button_to("Edit", edit_page_path(page), icon:"pencil") %>
          <%= button_to("Delete", page_path(page), method:"delete", confirm:"Are you sure you want to delete this page?", icon:"remove") %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/pages/edit.html.erb
<% page title:"Edit #{@page.name}", class:"form edit-wiki-page" %>

<% subtitle link_to("Manage Attachments", page_attachments_path(@page)) %>
<% subtitle link_to("Old Versions", page_versions_path(@page)) %>
<% subtitle button_to("Delete", page_path(@page), method:"delete", confirm:"Are you sure you want to delete this page?", class:"btn-danger", icon:"remove") %>
        
<%= form_for @page, url:page_path(@page), html:{multipart:true} do |f| %>
  <%= render_errors @page %>
  <%= render partial:"form", locals:{f:f} %>
<% end %>

app/views/pages/home.html.erb
<div class="page-content">
<%= raw @html %>
</div>

<%= available_page_actions(@page) %>

app/views/pages/index.html.erb
<% page title:'Pages' %>
<% subtitle link_to("Add Page", new_page_path) if can_edit? %>

<%= render "page_list" %>

app/views/pages/new.html.erb
<% page title:"New Page" %>

<%= form_for @page, html:{multipart:true} do |f| %>
  <%= render_errors @page %>
  <%= render partial:"form", locals:{f:f} %>
<% end %>

app/views/pages/not_found.html.erb
<% page title:"Not Found" %>

<p>Sorry, we can't seem to find this page.  Try again?</p>

app/views/pages/show.html.erb
<% page title:@page.name, class:"wiki-page #{@page.page_class}" %>

<% subtitle raw [available_page_actions(@page), tags_for_page(@page)].compact.join(" &nbsp; ") %>

<%= link_to image_tag(@page.thumbnail.url(:medium), class:"page-thumbnail"), @page.thumbnail.url if @page.thumbnail? %>

<div class="page-content">
<%= raw @html %>
</div>

<% if @page.attachments.size > 0 %>
  <div class="page-attachments">
    <h4>Attachments</h4>
    <ul>
      <% @page.attachments.each do |attachment| %>
        <% next if attachment.is_image? %>
        <li><%= link_to attachment.content_file_name, attachment.url %></li>
      <% end %>
    </ul>
    <ul class="thumbnails">
      <% @page.attachments.each do |attachment| %>
        <% next unless attachment.is_image? %>
        <li class="span2">
          <%= link_to image_tag(attachment.thumbnail), attachment.url, class:"thumbnail" %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if can_edit? %>
  <%= link_to_function "Add an Attachment", "$(this).hide().next().show()" %>
  <%= form_for [@page, @page.attachments.build], html:{multipart:true, style:"display:none;"} do |f| %>
    <%= f.file_field :content %>
    <%= f.submit "Upload", class:"btn btn-primary" %>
  <% end %>
<% end %>
<br/>

<hr style="clear:both"/>

<% if FB_APP_ID %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=179819392135321";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="<%= request.url %>" data-send="false" data-width="800" data-show-faces="true"></div>
<br/>
<br/>
<fb:comments href="<%= request.url %>" width="800px"></fb:comments>

<% end %>