config/routes.rb
Hsd::Application.routes.draw do
  root :to => "pages#home"

  resources :pages do
    resources :versions, :controller => "pages/versions"
    resources :attachments, :controller => "pages/attachments"
  end
  resources :tags
  resources :changes

  resources :files do
    get '*path', :action => 'show', :on => :collection
  end
  
  namespace :admin do
    resources :users do
      post :confirm, :on => :member
    end
  end

  resource :search, :controller => :search

  get "/sign_in", to:"sessions#new", as:"sign_in"
  get "/sign_out", to:"sessions#destroy", as:"sign_out"
  post "/welcome", to:"sessions#unlock", as:"unlock"
  match '/auth/:provider/callback', to:'sessions#create'
  match '/auth/failure', to:'sessions#failure'

  match "/index.html" => redirect("/")
  get '/home' => redirect("/")
  
  get    ':id' => 'pages#show', :as => :page
  put    ':id' => 'pages#update'
  delete ':id' => 'pages#destroy'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :pages
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :load_tag, except:[:index, :new, :create]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end
  
  def create
    Tag.create! params[:tag]
    redirect_to tags_path
  end

  def update
    @tag.update_attributes!(params[:tag])
    redirect_to tags_path
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end

  private

  def load_tag
    @tag = Tag.find(params[:id])
  end

end

app/helpers/tags_helper.rb
module TagsHelper
  def pages_for_tag(tag)
    redcloth = RedCloth.new("pages. #{tag.name}")
    redcloth.extend(WikiTags)
    raw redcloth.to_html(:textile, :refs_wiki_links)
  end
end

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-actions">
    <%= f.submit "Save", disable_with:"Saving...", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% page title:"Edit Tag" %>

<%= render "form" %>

app/views/tags/index.html.erb
<% page title:"Tags" %>

<% subtitle link_to("Add Tag", new_tag_path, icon:"file") if can_edit? %>

<table class="table">
  <% @tags.each do |tag| %>
    <tr>
      <td><%= link_to tag.name, tag %></td>
      <td>
        <%= button_to "Edit", edit_tag_path(tag), icon:"pencil" if can_edit? %>
        &nbsp;
        &nbsp;
        <%= button_to "Delete", tag, icon:"remove", class:"btn", method:"delete", confirm:"Are you sure you want to delete this tag?" if can_edit? %>
      </td>
    </tr>
  <% end %>
</table>

app/views/tags/new.html.erb
<% page title:"New Tag" %>

<%= render "form" %>

app/views/tags/show.html.erb
<% page title:"#{@tag.name} Pages" %>
<% subtitle link_to("Edit Tag", edit_tag_path(@tag)) if can_edit? %>

<%= pages_for_tag(@tag) %>