config/routes.rb
Hsd::Application.routes.draw do
  root :to => "pages#home"

  resources :pages do
    resources :versions, :controller => "pages/versions"
    resources :attachments, :controller => "pages/attachments"
  end
  resources :tags
  resources :changes

  resources :files do
    get '*path', :action => 'show', :on => :collection
  end
  
  namespace :admin do
    resources :users do
      post :confirm, :on => :member
    end
  end

  resource :search, :controller => :search

  get "/sign_in", to:"sessions#new", as:"sign_in"
  get "/sign_out", to:"sessions#destroy", as:"sign_out"
  post "/welcome", to:"sessions#unlock", as:"unlock"
  match '/auth/:provider/callback', to:'sessions#create'
  match '/auth/failure', to:'sessions#failure'

  match "/index.html" => redirect("/")
  get '/home' => redirect("/")
  
  get    ':id' => 'pages#show', :as => :page
  put    ':id' => 'pages#update'
  delete ':id' => 'pages#destroy'
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :versionable, :polymorphic => true
  belongs_to :author, :class_name => "User"
  
  def to_param
    version.to_s
  end

  def diff
    Differ.format = Differ::Format::HTML
    Differ.diff_by_line(body, previous ? previous.body : "").to_s
  end

  def previous
    return nil unless versionable
    @previous ||= versionable.versions.where(version:version - 1).first
  end
end

app/controllers/pages/versions_controller.rb
class Pages::VersionsController < ApplicationController
  before_filter :require_editor!
  before_filter :load_page
  
  def index
    @versions = @page.versions.order("created_at desc")
  end
  
  def show
    @version = @page.versions.find_by_version(params[:id]) || raise(ActiveRecord::RecordNotFound)
  end
  
  protected
  
  def load_page
    @page = Page.find_by_param(params[:page_id]) || raise(ActiveRecord::RecordNotFound)
  end
end

app/controllers/wiki/versions_controller.rb
class Wiki::VersionsController < ApplicationController
  before_filter :authenticate_user!, :internal_required
  before_filter :load_page
  
  def index
    @versions = @page.versions.order("created_at desc")
  end
  
  def show
    @version = @page.versions.find_by_version(params[:id]) || raise(ActiveRecord::RecordNotFound)
  end
  
  protected
  
  def load_page
    @page = Page.find_by_param(params[:wiki_id]) || raise(ActiveRecord::RecordNotFound)
  end
end

app/views/pages/versions/index.html.erb
<% page :title => "#{@page.name} Versions" %>

<ul>
  <% @versions.each do |version| %>
    <li><%= link_to "Version #{version.version} by #{version.author.name if version.author}", page_version_path(@page, version) %></li>
  <% end %>
</ul>

app/views/pages/versions/show.html.erb
<% page :title => "#{@page.name} Version #{@version.version}" %>

<p>
  <%= link_to "Back to versions", page_versions_path(@page) %> |
  <%= link_to_if @version.version > 0, "Previous version", page_version_path(@page, @version.version - 1) %> |
  <%= link_to_if @version.version < @page.version, "Next version", page_version_path(@page, @version.version + 1) %>
</p>

<h2>Author</h2>
<p><%= @version.author.name if @version.author %></p>

<h2>Body</h2>
<span class="value"><%= simple_format @version.body %></span>